### ISSUE TITLE
About minimum cpu requirement

### ISSUE THREAD

**Issue by AlbertoOsorio** [epi2me-labs/wf-human-variation#150]
### Ask away!

Hi. I wanted to try this specific epi2me workflow so I executed it with the demo data with virtualization for it to run on my hardware, an M2 pro station. It went fine. 

I performed basecalling with standalone Dorado for arm of human pod5, I then ran the rest of the workflow with the docker virtualization. This time the workflow stopped at the very start because of an unmet number of CPUs, M2 pro having only 10. I understand that the demo data is very low volume, still, I wanted to ask if this requirement can be edited even if it brings deep performance issues., as the M2 is my only machine available

Thanks!

**Comment by cjw85** [comment]
The minimum requirements are set as they are deliberately so. They are what we have tested and verified to be required in order to provide adequate compute performance.

Further the workflow does not support ARM processors. You may have some success running on Apple hardware (through the magic of Rosetta) but it is not something we support.
