### ISSUE TITLE
Multi-sample analysis and FASTQ starting files

### ISSUE THREAD

**Issue by SergeWielhouwer** [epi2me-labs/wf-human-variation#199]
Hi,

Thanks for developing wf-human-variation.

I was wondering why this workflow does not support a samplesheet for multi-sample analysis, which is common for many nextflow workflows (e.g. nf-core). This allows a user to get a comprehensive overview of a run through a single nextflow report. For multiple sample analysis, do you need to run this workflow multiple times in a separate manner (e.g. a for loop)? What options would you recommend?

Also, if starting from multiple sample FASTQs or CRAMs, would you recommend converting them to uBAM prior to analysis, as alignment is performed anyways?

Looking forward to your ideas.

Best regards,

Serge

**Comment by cjw85** [comment]
Hi Serge,

This has been on the todo list for a while. The workflow was written prior to when we standardised handling multiple samples across our workflows.

It's not completely trivial to add the support now due to how Nextflow manages hierarchical compute tasks. Essentially, its going to involve touching all parts of the code and ensuring that all Nextflow operations understand "sample_id" as a primary key when aggregating data. I wrote about the difficulties of this previously [here](https://labs.epi2me.io/two-years-of-nextflow/#intuition-and-dataflow).

We've delayed the implementation as long as possible therefore after determining the added value isn't huge: all compute across samples would be independent so conceptually running nextflow multiple times would achieve much the same effect (and as explained above, keeping that compute independent in nextflow is rather annoying to retrofit!). The only added thing might be that we produce a multi-sample VCF right at the end.

Its definitely a feature we want to add when time permits.

**Comment by RenzoTale88** [comment]
A small add to what @cjw85 said, if you are starting from multiple FASTQ files, you can align them using our [wf-alignment](https://git.oxfordnanolabs.local/epi2melabs/workflows/wf-alignment/) workflow. If instead you start from an aligned CRAM file, you can simply convert it to BAM and, if the reference is correct, then it would skip the alignment stage altogether.

**Comment by SergeWielhouwer** [comment]
Hi Chris and Andrea,

Glad to hear that multi-sample support will be added somewhere in the future! I can understand the difficulties that one can encounter when analysing multiple samples, especially while also trying to split every sample in chunks and aggregate everything in the end. 

I will run nextflow multiple times for now and try out wf-alignment for running minimap2 in parallel.

Thanks,

Serge
