### ISSUE TITLE
[Bug]: Empty fail.cram from align_and_qsFilter

### ISSUE THREAD

**Issue by ymcki** [epi2me-labs/wf-human-variation#54]
### What happened?

I had several run with the 1.6.0 workflow. All of them gave me empty ${read.baseName}.fail.cram

I run the same command in align_and_qsFilter at the command line and I can recover the fail.cram correctly.

I suspect this might be due to wf_dorado forgot to return the fail.cram

    emit:
        chunked_pass_crams = crams.pass
        pass = pass
        fail = fail

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

1.6.0

### Relevant log output

```shell
I think this is a serious bug. Please fix it in your next release.
```

**Comment by SamStudio8** [comment]
Hi @ymcki, are you saying the files were completely empty, or these files are valid CRAM files with zero entries? Can you share the `align_and_qsFilter` command you ran to recover the fail.cram files?

**Comment by ymcki** [comment]
The fail.cram is valid cram but no entries when you run samtools view. 

As to the commands I used, I first combine the ubams in the subdirectory of workspace. Then run samtools with minimap2

samtools merge -o ABC.ubam `find workspace/ -mindepth 1 ! -type l -name "*.ubam"`
samtools bam2fq -@ 10 -T 1 ABC.ubam | minimap2 -y -t 80 -ax map-ont hs38D.mmi - | samtools sort -@ 30 | samtools view -e '[qs] >= 10' --output pass.cram --unoutput fail.cram -O CRAM --reference hs38D.fa -

**Comment by SamStudio8** [comment]
Hi @ymcki. I am unable to reproduce this. The workflow outputs a SAMPLE.fail.cram with reads in when I use [one of our data sets](https://labs.epi2me.io/askenazi-kit14-2022-12/). Is it possible that your workspace contains ubam files from different invocations of wf-human-variation? 

What happens if you lower the value of `--qscore_filter` (the default is 10).

Please note the code example you have provided is intentional, `chunked_pass_crams` is not used by wf-human-variation. The `pass` and `fail` channels contain the merged CRAM files used by the workflow.

**Comment by ymcki** [comment]
Seems like I can't observe the empty fail.cram problem any more with 1.6.1. So I think this issue can be closed.
